Repository hackroid/tg-dumb-bot, pull requests merged in 2023-03, with the labels that each got.

#9 add Dockerfile docker-compose.yml
  Dockerfile
  docker-compose.yml
Labels: enhancement

#16 .env bug fixed
  Dockerfile
  run.sh
Labels: bug

#18 Create .github/workflows/go.yml
  .github/workflows/go.yml
Labels: enhancement

#19 restructure project
  .github/workflows/go.yml
  .gitignore
  Dockerfile
  README.md
  app/main/main.go
  go.sum
  main/main.go
  pkg/botserver/botserver.go
  pkg/constants/constants.go
  pkg/handler/msghandler.go
Labels: enhancement

#21 restructure workflow
  .github/actions/deploy/action.yml
  .github/actions/docker/action.yml
  .github/actions/go/action.yml
  .github/workflows/go.yml
  .github/workflows/pull_request.yml
  .github/workflows/pull_request_closed.yml
  .github/workflows/push.yml
Labels: enhancement

#36 Abstract Handler Factory and Command Behavioral Pattern
  app/main/main.go
  assets/samplemsg/image.json
  assets/samplemsg/image_caption.json
  assets/samplemsg/image_caption_fwd.json
  assets/samplemsg/text.json
  assets/samplemsg/text_cmd.json
  assets/samplemsg/text_group.json
  pkg/botserver/botserver.go
  pkg/datatype/msgio.go
  pkg/handler/handlerfactory.go
  pkg/handler/msghandler.go
  pkg/static/command.go
  pkg/static/text.go
Labels: bug

#37 add FenKeng & close stdin
  .github/actions/go/action.yml
  Dockerfile
  README.md
  assets/web/sample_header.json
  go.mod
  go.sum
  pkg/botserver/botserver.go
  pkg/handler/msghandler.go
  pkg/static/command.go
  pkg/static/crawler.go
  pkg/utils/fileio.go
Labels: feature request

#41 crawler optimized
  pkg/static/command.go
  pkg/static/crawler.go
Labels: enhancement

#46 add release workflow
  .github/actions/deploy/action.yml
  .github/workflows/release.yml
Labels: bug
